#!/bin/sh

# This little helper script is needed for systems where the python 2.x binary is called python2. (This is tested on Arch Linux)

PYTHON="/usr/bin/python"

if [ -x "/usr/bin/python2" ]; then
    PYTHON=""/usr/bin/python2""
fi

PRG="$0"

# need this for relative symlinks
while [ -h "$PRG" ] ; do
   PRG=`readlink "$PRG"`
done

$PYTHON "`dirname "$PRG"`/encode2all.py" $@
